"""machine

Revision ID: 56b218f585f9
Revises: 4f338dbcc0b3
Create Date: 2021-04-24 11:33:51.087059

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '56b218f585f9'
down_revision = '4f338dbcc0b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machine',
                    sa.Column('id', sa.String(length=36), nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
                              nullable=True),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
                              nullable=True),
                    sa.Column('deleted', sa.Boolean(), nullable=True),
                    sa.Column('deleted_at', sa.DateTime(), nullable=True),
                    sa.Column('name', sa.String(length=500), nullable=True),
                    sa.Column('host_name', sa.String(length=500), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('machine')
    # ### end Alembic commands ###
