"""directory

Revision ID: ec72685b6da9
Revises: 56b218f585f9
Create Date: 2021-04-28 22:38:22.071098

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ec72685b6da9'
down_revision = '56b218f585f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('directory',
                    sa.Column('id', sa.String(length=36), nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
                              nullable=True),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
                              nullable=True),
                    sa.Column('deleted', sa.Boolean(), nullable=True),
                    sa.Column('deleted_at', sa.DateTime(), nullable=True),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('machine_id', sa.String(length=36), nullable=False),
                    sa.ForeignKeyConstraint(['machine_id'], ['machine.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('machine_id')
                    )
    op.drop_index('ix_user_status', table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
                    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(),
                              server_default=sa.text("timezone('utc'::text, CURRENT_TIMESTAMP)"), autoincrement=False,
                              nullable=True),
                    sa.Column('updated_at', postgresql.TIMESTAMP(),
                              server_default=sa.text("timezone('utc'::text, CURRENT_TIMESTAMP)"), autoincrement=False,
                              nullable=True),
                    sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
                    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
                    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
                    sa.Column('avatar_url', sa.VARCHAR(length=3000), autoincrement=False, nullable=True),
                    sa.Column('old_id', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name='user_pkey')
                    )
    op.create_index('ix_user_status', 'user', ['status'], unique=False)
    op.drop_table('directory')
    # ### end Alembic commands ###
